# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20180611_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='TipoHab',
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
